# Generated by Django 5.0.4 on 2024-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_created_at_move_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="player1",
            new_name="player",
        ),
    ]
