# Generated by Django 5.0.4 on 2024-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_move_move_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_winner",
            field=models.CharField(
                choices=[
                    ("player", "Player"),
                    ("computer", "Computer"),
                    ("tie", "Tie"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
